### ISSUE TITLE
Examples in production?

### ISSUE THREAD

**Issue by A7DC** [jamonserrano/plumber-sass#11]
Hi there,

Thanks for taking the time to create this awesome plugin - I'm just wondering if you've got any real-world examples to share, specifically with complicated web apps with lots of component?

I'm thinking of using this for a betting application and would be interested to see how it works at scale. 

Thanks again!

**Comment by jamonserrano** [comment]
Hi, thanks for your interest in the project!

I haven't followed real-world usage of it, I suggest checking out the dependents to see if you find anything relevant: https://github.com/jamonserrano/plumber-sass/network/dependents

When I was developing this project I mostly intended it for text-heavy pages like blogs and I'm not sure if it would hold up in a complex application with forms, buttons, menus, etc.. In those cases it might be better to align not the text but the UI components, so a _regular_ grid could be more suitable for the job. (I would personally recommend the 8-point grid.)

Hope this helps, if you have any more questions, let me know!

**Comment by A7DC** [comment]
Thank you for your response @jamonserrano, it's much appreciated!
