### ISSUE TITLE
Add baseline ratio calculation example

### ISSUE THREAD

**Issue by nevvkid** [jamonserrano/plumber-sass#4]
Hey. 
Thank you for building this project.
I have used [sassline](https://sassline.com/) before.
Right now i am trying to implement your tool in a real life project.

The font i want to use is called [Lelo](https://camelot-typefaces.com/lelo) 

I got the following information from the Typedesigner:
Ascender: 1032
Descender: -328
Caps height: 648
x height: 468
1000 Units pro EM

So if i want to do the math.
(UnitsPerEm − hhea.Ascender − hhea.Descender) / (2 × UnitsPerEm)

[1000 - 1032 - (-328)] / [2 x 1000]
[1000 - 1360] / [2 x 1000]
-360 / 2000
= -0.18

Using [the measure tool ](https://jamonserrano.github.io/plumber-sass/measure/) i get a value of 0.268

Maybe you can point me to a solution. Thank you!

**Comment by jamonserrano** [comment]
Hi,

Thanks for the feedback!

The Ascender and Descender values need to come from the **hhea** (horizontal header) OpenType table. These usually differ from the values in the font summary – to my knowledge those come from the OS/2 table.

E.g. for Roboto Black the values are the following:

hhea.Ascender | Ascender | hhea.Descender | Descender
------------- | -------- | -------------- | ---------
**1900** | 1536 | **-500** | -512

So the calculation is (with 2048 units/em):

`(2048 - 1900 - (-500)) / (2 x 2048) = 0,158203125`

I recommend you open the font file in a font editor (e.g. RoboFont) or just upload it to the [opentype.js font inspector](http://opentype.js.org/font-inspector.html) and check the hhea table ([see attached screenshot](https://cloud.githubusercontent.com/assets/142130/21652964/40ef35b2-d2af-11e6-9d68-110de5cc97e6.png)). If you still get the same values – this is rare but possible – please use the value from the measure tool. In my tests manual measurement still provides accurate results for font sizes up to a few hundred pixels.

Hope this helps!

![opentype-robotoblack](https://cloud.githubusercontent.com/assets/142130/21652964/40ef35b2-d2af-11e6-9d68-110de5cc97e6.png)

**Comment by nevvkid** [comment]
Hey! Thanks for the fast response.

I have checked with the opentype.js tool. Getting the same values as i put in my example calculation. 
Is it possible to have a negative value as a result?

One other thing i realised is.
For the desktop [.otf] font the measure tool result is 0.268 
If i use activate the [.ttf] webfont in my system i get a result of 0.148

So i don't know really what to use: 0.268 or 0.148 or -0.18

**Comment by jamonserrano** [comment]
In this case you should use the value from the measure tool with the webfont (0.148) as this will be served to the users of your site.

**Comment by nevvkid** [comment]
Thanks. I will do that. Looks ok > With a grid height of 10px and your settings from https://github.com/jamonserrano/plumber-sass/blob/gh-pages/scss/docs/_typography.scss it works half way....

But not sure about about how to use it with my standard base-font-size of 1em. Have to make some more tests. Maybe it would be nice to have the possibility to not have the grid-height as the font-size on the <html> element. Maybe fractions like teehan+lax used to do it - [see here ](http://www.teehanlax.com/blog/designing-faster-with-a-baseline-grid/)
As well i have to see how to calculate for a modular scale and make it responsive in my environment using [bourbon](http://bourbon.io/) and [bitters](http://bitters.bourbon.io/)

Should i close the "issue" is there another way to talk about the project and related ideas (if you are interested in that)?

**Comment by jamonserrano** [comment]
Yes, let's close this issue and start a new one for the other discussion.
