### ISSUE TITLE
how bout a post-css version?

### ISSUE THREAD

**Issue by selfagency** [jamonserrano/plumber-sass#6]
it'd be great to see this as a postcss plugin in addition to an scss mixin as many folks have begun to migrate from sass to postcss

**Comment by jamonserrano** [comment]
Good idea!

I've created a new repository for the plugin: https://github.com/jamonserrano/postcss-plumber

I am not very familiar with postcss, so please leave feedback on the proposed syntax in this ticket: https://github.com/jamonserrano/postcss-plumber/issues/1

**Comment by selfagency** [comment]
awesome! just saw this. will take a crack at it.
