### ISSUE TITLE
$line-height parameter must be a positive unitless integer, got 1.5 instead

### ISSUE THREAD

**Issue by clearfickle** [jamonserrano/plumber-sass#7]
I'm not allowed to have a line-height of `1.5` 😢

**Comment by pebcakerror** [comment]
Is is possible to achieve a similar vertical rhythm + modular scale similar to https://www.gridlover.net/try

**Comment by jamonserrano** [comment]
Thanks for your feedback @clearfickle!

The point of the baseline grid is that all line heights are whole multiples of the grid height. If you need a 1.5 line height I suggest you halve the grid height so the line height multiplier in question becomes 3.
E.g. change

```css
@include plumber {
  $grid-height: 1rem,
  $line-height: 1.5
}
```

to

```css
@include plumber {
  $grid-height: 0.5rem,
  $line-height: 3
}
