### ISSUE TITLE
Calculation method for webfonts

### ISSUE THREAD

**Issue by ghost** [jamonserrano/plumber-sass#8]
Hi there,

I'm unable to download webfonts from Typekit/Fonts.com. Any advice on how to calculate baseline ratio with lesser-known typefaces?

Thanks!

**Comment by ghost** [comment]
Update: I tried [getBaseline.js](https://github.com/designmeme/getBaseline.js) but I can't figure out how to generate a return. [Here's the fiddle.](https://jsfiddle.net/dolanbrendan12/s167ngr3/7/)

Any help would be amazing!

Thanks,

Brendan

**Comment by jamonserrano** [comment]
@dolanb12 On a Mac you can sync Typekit fonts with the Adobe Creative Cloud Desktop app and then - although they don't show up in FontBook - you should be able to measure the baseline ratio by entering the font name here: https://jamonserrano.github.io/plumber-sass/measure/

I've just synced Amaranth Italic and as you can see in the screenshot it is successfully loaded in the measure tool.
<img width="500" alt="font_synced" src="https://user-images.githubusercontent.com/142130/44518087-aa43af80-a6c9-11e8-902b-f41efdbdb49c.png">
![measure](https://user-images.githubusercontent.com/142130/44518207-f8f14980-a6c9-11e8-80ae-8e601a013769.png)

I hope this helps!

**Comment by ghost** [comment]
Amazing, thanks!

I was under the impression that "Local Font" meant "system font" (arial, verdana, etc.). 

My mistake. What a great tool!
